### ISSUE TITLE
REQUEST: Right Side Menu Default view option

### ISSUE THREAD

**Issue by GambetTV** [ironmonk88/monks-common-display#3]
There's a lot of functionality lost when activating this module for the Common Display, mostly when it comes to the menu. Sometimes there are settings I might want to configure, or I might want to log out, or change the volume on a playlist or ambient sounds. But there's no way to access this without clunkily going in on the DM's computer, changing the username so it releases its hold on the Common Display player, then refreshing that scene.

It'd be great if there was an option, either a toggle on the DM's side, even if it were in the Settings, or a button on the Common Display, to keep the right side menu to its defaults if we want.

**Comment by ironmonk88** [comment]
Partial Rebuild of the module.
There's now a button on the toolbar that will let you turn on and off the display mid game.  You can now select players from a list rather than typing the name into a comma delimited list in settings.
I've also added some optimization so that a player that's been set as display previously will load immediately without the UI.

And fixed an issue where you couldn't clear out the images from Display.

Released with version 1.0.1
